name: Update Planet SymPy

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: planet-sympy:latest

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Run update script
        run: |
          docker run --rm \
            -e SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}" \
            -v ~/.ssh:/root/.ssh \
            planet-sympy:latest